#!/bin/bash

# Configuration of a brand new Rev C BBB - Part 2
# JFDuval 03/19/2015

echo "[FlexSEA] Configuring the SPI driver and pins"
dtc -O dtb -o BB-SPI0-01-00A0.dtbo -b 0 -@ BB-SPI0-01-00A0.dts
cp BB-SPI0-01-00A0.dtbo /lib/firmware/
echo BB-SPI0-01 > /sys/devices/bone_capemgr.*/slots
cd /home/debian/Desktop/

#End of script #2
